### ISSUE TITLE
Bug: Saving in 3.0 a record not working with - dash in the contenttype name

### ISSUE THREAD

**Issue by evertalbers** [bolt/docs#407] opened 2016-05-18 07:23 UTC
I have not tested this extensively, but I'm pretty sure that putting a '-' in a contenttype name throws an error when saving a record. Things did work without the '-' in 3.0.

Needless to say that this has consequences for this part of the documentation.

**Comment by GawainLynch** [comment] 2016-05-18 07:28
Related https://github.com/bolt/bolt/pull/5299

**Comment by SahAssar** [comment] 2016-05-18 08:51
Just to clarify, the part of the docs that recommend using dashes in contenttypes is "Building Multilingual Websites with Bolt"...

**Comment by PhillippOhlandt** [comment] 2016-08-24 21:10
Whats the plan on this? Fixing the example or waiting for the proper solution in core?

**Comment by GawainLynch** [comment] 2016-08-24 21:17
> Whats the plan on this? Fixing the example or waiting for the proper solution in core?

Well, we can wait on the 3.3 work, which should address most (all?) of it, or preface that with a docs update … it's kinda a sticky place as the problem is a real bug, so what are we documenting :disappointed:

**Comment by PhillippOhlandt** [comment] 2016-08-24 21:18
Yeah then let's wait on this until it's fixed in core.

**Comment by GawainLynch** [comment] 2017-02-24 04:03
Fixed in core as of I think 3.1

**Closed by GawainLynch** 2017-02-24 04:03 UTC
