### ISSUE TITLE
'localhost' in link 'Getting the most...' in news about 2.0.6

### ISSUE THREAD

**Issue by gwbonline** [bolt/docs#146] opened 2015-02-10 08:24 UTC
The news about 2.0.6 contains a link (Getting the most out of the ‘Select’ fieldtype) that has 'localhost' in it...

And... it's my birthday!

**Comment by rarila** [comment] 2015-02-10 08:32
:birthday: :gift: :tada:

**Comment by GawainLynch** [comment] 2015-02-10 08:53
:birthday: :gift: :tada:

**Comment by GawainLynch** [comment] 2015-02-10 08:59
I am guessing you've got a cached copy of the news item as it seems to be OK.

**Comment by gwbonline** [comment] 2015-02-10 09:12
No, everything is cleared when I close my browser (cookies, history, etc.). I read the article right now and there is still a link with localhost in it. 

https://bolt.cm/newsitem/minor-update-bolt-206-released

**Comment by rarila** [comment] 2015-02-10 09:16
Yes, I can confirm this

**Comment by bobdenotter** [comment] 2015-02-12 19:59
I am a dumbass. Fixed now, thanks for noticing.. 

![do not dumb here](https://cloud.githubusercontent.com/assets/1833361/6175783/09c1a272-b2fa-11e4-8a06-097f196bcdf1.jpg)

**Closed by bobdenotter** 2015-02-12 19:59 UTC
