### ISSUE TITLE
documentation is not up to date / complete / sufficient

### ISSUE THREAD

**Issue by jadwigo** [bolt/docs#75] opened 2014-07-04 15:51 UTC
The documentation is old, insufficient or incomplete 

Some things I'm missing or look wrong to me

**Getting started:**
- [x] config_local.yml and related tips

**Working with bolt:**
- [x] content types configuration ( `contenttypes.yml` )
  - [x] all fields in a readable format
  - [x] file uploads / file lists

**Templating:**
- [x] query parameters for use in templates - `setcontent x where { a : b }` and other constructions like that 

**Development:**
- [x] building a twig filter
- [x] creating your own nut commands
- [x] all mentions of `\util::foo`

**Extensions:**
- [x] building an extension is not consistent with most included extensions
- [x] what is the recommended way to set up a database connection in an extension
- [x] saving and loading content from an extension
- [ ] what documentation for an extension is recommended
- [ ] how to send a mail from within an extension
- [x] how to add a script/css/twig asset from an extension

**Comment by SahAssar** [comment] 2015-10-18 08:52
Set " what is the recommended way to set up a database connection in an extension" and "saving and loading content from an extension" as checked, since those are in the storage part of the docs now.

**Comment by GawainLynch** [comment] 2017-02-24 04:08
Most of this is all done now, and the issue is 3 years old.

Anyone wanting to  assist writing more docs is most welcome, but closing for SnR.

**Closed by GawainLynch** 2017-02-24 04:08 UTC
Labels: bug
